@startuml screen-transition-diagram

[*] --> トップページ
トップページ: ログインして使うのみなので、ほぼ必要なし

トップページ --> ログイン画面
ログイン画面: メールアドレス
ログイン画面: パスワード

ログイン画面 --> 運営者管理画面:ログイン画面/ログイン
state 運営者管理画面 {
    [*] --> 運営者ダッシュボード
    運営者ダッシュボード: 各ページへのリンク。統計データ。

    運営者ダッシュボード --> ユーザー管理画面
    ユーザー管理画面: ユーザー追加・編集・削除

    運営者ダッシュボード --> 問題管理画面

    運営者ダッシュボード --> 診断結果管理画面
}

ログイン画面 ---> インストラクター管理画面:ログイン画面/ログイン
state インストラクター管理画面 {
    [*] --> インストラクターダッシュボード
    インストラクターダッシュボード: 各ページへのリンク。統計データ。

    インストラクターダッシュボード --> 診断作成画面
    診断作成画面: 設問選択機能
    診断作成画面: 診断URL発行機能（予約発行・即時発行）
    診断作成画面: QRコード生成機能
    診断作成画面: 時間制限設定機能
    診断作成画面: ID・パスワード設定機能

    インストラクターダッシュボード --> 診断結果閲覧画面
    診断結果閲覧画面: グループ（診断した日やセミナー毎のグループ）別閲覧機能
}

診断作成画面 --> 会員登録画面:一般利用客がアクセス/インストラクターが発行したURL
会員登録画面 --> 一般利用客管理画面:ログイン画面/ログイン
会員登録画面: メールアドレス
会員登録画面: パスワード
会員登録画面: ※会員登録を必要とするか検討中
state 一般利用客管理画面 {
    [*] --> カラー診断画面
    カラー診断画面 --> 診断結果画面
}

@enduml
