name: CI

on: ['push', 'pull_request']

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    # laravelプロジェクトのあるディレクトリに変更
    # defaults:
    #   run:
    #     working-directory: ./example-app

    steps:
      - uses: actions/checkout@v3

      - name: cp env
        run: cp .env.local .env

      - name: cp env.testing
        run: |
          sed -e "s/DB_HOST=mysql/DB_HOST=mysql.test/" ./.env > ./.env.testing
          sed -i.bak -e "s/APP_ENV=local/APP_ENV=testing/" ./.env.testing
          sed -i.bak -e "s/DB_PORT=3306/DB_PORT=3306\nFORWARD_DB_PORT=3300/" ./.env.testing
          rm -f ./.env.testing.bak

      - name: composer install
        run: docker run --rm -u "$(id -u):$(id -g)" -v $(pwd):/var/www/html -w /var/www/html laravelsail/php81-composer:latest composer install --ignore-platform-reqs

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: npm install
        run: npm install

      # 先に起動しておく
      - name: start mysql
        run: ./vendor/bin/sail up -d mysql

      - name: start
        run: ./vendor/bin/sail up -d

      - name: generate key
        run: ./vendor/bin/sail artisan key:generate

      - name: migrate
        run: ./vendor/bin/sail artisan migrate:fresh --seed

      - name: build
        run: ./vendor/bin/sail npm run build

      - name: test
        # run: ./vendor/bin/sail test
        run: make test
