name: Larastan

on:
  pull_request:
    paths:
      - "**.php"

jobs:
  larastan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # PHP環境のセットアップ
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2, cs2pr

      # setup-phpにphpstanはあるがLarastanがなさそうなので、個別にインストール
      - name: Larastan install
        run: composer require nunomaduro/larastan --dev

      # リポジトリの中で今回のPushで変更があったファイルだけを取得し、スペースでつなげた文字列を取得する
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.3

      # PHPStanを実行。解析レベルは10段階中5とし、解析対象は上で取得したファイル名リストの変数を使う
      - name: Run PHPStan
        run: vendor/bin/phpstan analyze --memory-limit=-1 -l 5 -c vendor/nunomaduro/larastan/extension.neon ${{ steps.changed-files.outputs.all_changed_files }}
